version: "4.3"

networks:
  laravel:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER: ${USER:-youruser}
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html:delegated
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - laravel

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER: ${USER:-youruser}
    container_name: php
    volumes:
      - ./www:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER: ${USER:-youruser}
    container_name: composer
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-youruser}
    command: ["composer", "install"]
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: npm
    volumes:
      - ./www:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    command: ["npm", "install"]
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER: ${USER:-youruser}
    container_name: artisan
    volumes:
      - ./www:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    command: ["php", "/var/www/html/artisan", "migrate"]
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel

  phpmin:
    image: phpmyadmin:latest
    container_name: phpmin
    restart: unless-stopped
    ports:
      - "8989:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - laravel
